// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_SubmitEvent_FullMethodName  = "/agent.AgentService/SubmitEvent"
	AgentService_SubmitEvents_FullMethodName = "/agent.AgentService/SubmitEvents"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Unary RPC retained for compatibility
	SubmitEvent(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*SubmitEventResponse, error)
	// Client-side streaming RPC for batching and reliable ingestion
	SubmitEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventEnvelope, SubmitEventAck], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) SubmitEvent(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*SubmitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitEventResponse)
	err := c.cc.Invoke(ctx, AgentService_SubmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubmitEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventEnvelope, SubmitEventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_SubmitEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventEnvelope, SubmitEventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubmitEventsClient = grpc.ClientStreamingClient[EventEnvelope, SubmitEventAck]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Unary RPC retained for compatibility
	SubmitEvent(context.Context, *EventEnvelope) (*SubmitEventResponse, error)
	// Client-side streaming RPC for batching and reliable ingestion
	SubmitEvents(grpc.ClientStreamingServer[EventEnvelope, SubmitEventAck]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) SubmitEvent(context.Context, *EventEnvelope) (*SubmitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEvent not implemented")
}
func (UnimplementedAgentServiceServer) SubmitEvents(grpc.ClientStreamingServer[EventEnvelope, SubmitEventAck]) error {
	return status.Errorf(codes.Unimplemented, "method SubmitEvents not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_SubmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitEvent(ctx, req.(*EventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubmitEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SubmitEvents(&grpc.GenericServerStream[EventEnvelope, SubmitEventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubmitEventsServer = grpc.ClientStreamingServer[EventEnvelope, SubmitEventAck]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvent",
			Handler:    _AgentService_SubmitEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitEvents",
			Handler:       _AgentService_SubmitEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent/agent.proto",
}
